### ISSUE TITLE
Basic Configuration of Glance Using StorageGRID Webscale as a Glance Backing Store in NetApp OpenStack Docs

### ISSUE THREAD

**Issue by amit0701** [NetApp-openstack-dev/openstack-docs#5]
- [x ] This doc is inaccurate in this way: ______
S3 protocol for Glance stores is removed from Newton release.  So SGWS with S3 as a protocol wouldn't work
- [ ] This is a doc enhancement request.
- [ x] I have a fix to the document that I can paste below including example: input and output. 
I could get it working with SGWS as Glance store with Swift protocol, I had to use Glance v1 API though. (which is deprecated - not sure if it is the right way). I found a bug when using Glance v2 API.

-----------------------------------
Release: 2017.2 on 2017-09-20 16:01
SHA: 43a53f507eacaaa2ad36ab9bdb304adae3a21472
Source: https://github.com/NetApp-openstack-dev/openstack-docs/glance/configuration/section_glance-standard-config-sg.rst
Current URL: https://netapp-openstack-dev.github.io/openstack-docs/pike/glance/configuration/section_glance-standard-config-sg.html
Filed against: PIKE

**Comment by mchad1** [comment]
The following bug has been opened by Amit with Redhat describing the issue with the V2 API:
https://bugzilla.redhat.com/show_bug.cgi?id=1494611

**Comment by mchad1** [comment]
Here is the latest regarding the question of supportability of SG and Glance:

As we know:
-S3 is no longer present in the glance-api.
-Per Redhat, the v2 api ALWAYS results in chunking.  If the image size is less than max file size, one chunk is sent as well as a manifest.  This differs from v1 where chunking does not occur until maximum file size is met. 
-The v1 glance api is targeted for removal after Pike, its been saying that since at least Newton.    Funny, the pike release api.log says (api v1 will be removed on or after pike).

What does this mean:
It means that unless we are get segmentation support with Swift, the StorageGRID and glance use case is near its end of life.  We have been suggesting v2 glance api for years by the way 

I’d suggest, based on the above, that we remove storage grid from our glance documentation.

**Comment by mchad1** [comment]
I am removing StorageGRID from the documentation post Mitaka.
